import type { StoreGame } from '../types/storeTypes'

export const STORE_GAMES: StoreGame[] = [
  {
    id: 'color-sort',
    name: 'Color Sort 3D',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationValue: '3-5',
    playerValue: '1',
    path: '/color-sort',
    tone: '#e0452a',
    accent: '#2ec4b6',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'uno',
    name: 'UNO',
    category: 'cards',
    categoryLabel: 'Cards',
    durationValue: '10',
    playerValue: '2-4',
    path: '/uno',
    tone: '#8b5cf6',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'chess',
    name: 'Chess',
    category: 'board',
    categoryLabel: 'Board',
    durationValue: '15',
    playerValue: '1-2',
    path: '/chess',
    tone: '#769656',
    accent: '#eeeed2',
    mode: 'bot',
    modeLabel: 'Stockfish',
    isAvailable: true,
  },
  {
    id: 'animal-matching',
    name: 'Animal Matching',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationValue: '5',
    playerValue: '1',
    path: '/animal-matching',
    tone: '#2f6d4f',
    accent: '#f0b429',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'maze-runner',
    name: 'Labirin Kumbang',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationValue: '3',
    playerValue: '1',
    path: '/maze-runner',
    tone: '#e0452a',
    accent: '#f6c945',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'congklak',
    name: 'Congklak',
    category: 'board',
    categoryLabel: 'Board',
    durationValue: '10',
    playerValue: '1-2',
    path: '/congklak',
    tone: '#6d4bc4',
    accent: '#f0b429',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'dots-and-boxes',
    name: 'Dots & Box',
    category: 'board',
    categoryLabel: 'Board',
    durationValue: '5',
    playerValue: '1-2',
    path: '/dots-and-boxes',
    tone: '#3b6fd4',
    accent: '#e0452a',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'othello',
    name: 'Othello',
    category: 'board',
    categoryLabel: 'Board',
    durationValue: '10',
    playerValue: '1-2',
    path: '/othello',
    tone: '#1f6d4f',
    accent: '#f2ede1',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'gomoku',
    name: 'Gomoku',
    category: 'board',
    categoryLabel: 'Board',
    durationValue: '8',
    playerValue: '1-2',
    path: '/gomoku',
    tone: '#c9a06a',
    accent: '#e0452a',
    mode: 'bot',
    modeLabel: 'vs Bot',
    isAvailable: true,
  },
  {
    id: 'rubik',
    name: 'Rubik 3D',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationValue: '5',
    playerValue: '1',
    path: '/rubik',
    tone: '#e0452a',
    accent: '#f0b429',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'tetris',
    name: 'Tetris',
    category: 'arcade',
    categoryLabel: 'Arcade',
    durationValue: '5',
    playerValue: '1',
    path: '/tetris',
    tone: '#3b6fd4',
    accent: '#f0b429',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'game-2048',
    name: '2048',
    category: 'puzzle',
    categoryLabel: 'Puzzle',
    durationValue: '5',
    playerValue: '1',
    path: '/game-2048',
    tone: '#e8862c',
    accent: '#f0b429',
    mode: 'solo',
    modeLabel: 'Solo',
    isAvailable: true,
  },
  {
    id: 'slither',
    name: 'Slither 3D',
    category: 'arcade',
    categoryLabel: 'Arcade',
    durationValue: '5-10',
    playerValue: '2-10',
    path: '/slither',
    tone: '#2ec4b6',
    accent: '#f0b429',
    mode: 'online',
    modeLabel: 'Online',
    isAvailable: true,
  },
]
